apiVersion: apps/v1
kind: Deployment
metadata:
  name: canisue
spec:
  selector:
    matchLabels:
      app: canisue
  replicas: 2
  template:
    metadata:
      labels:
        app: canisue
    spec:
      containers:
      - name: canisue
        image: junanqu/flask-template:v1
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        - name: DATABASE_URL
          value: postgresql://localhost/my_app_db
        ports:
        - containerPort: 5000
